### ISSUE TITLE
units fails to compile with `Rcpp 1.0.14`

### ISSUE THREAD

**Issue by jtlandis** [r-quantities/units#421]
I don't know if this is something that should really be an issue, but in attempting to install this package for `sf`, it would often fail.

After updating to `Rcpp 1.1.0` I was able to install everything. Perhaps the package dependency for Rcpp should be updated?

**Comment by mirh** [comment]
```
In file included from /usr/lib/R/library/Rcpp/include/Rcpp.h:49,
                 from tokenizer.cpp:147:
/usr/lib/R/library/Rcpp/include/Rcpp/Function.h: In constructor ‘Rcpp::Function_Impl<StoragePolicy>::Function_Impl(const std::string&, const std::string&)’:
/usr/lib/R/library/Rcpp/include/Rcpp/Function.h:75:65: error: ‘R_NamespaceRegistry’ was not declared in this scope [-Wtemplate-body]
   75 |             Shield<SEXP> env(R_getVarEx(Rf_install(ns.c_str()), R_NamespaceRegistry, FALSE, R_UnboundValue));
```
FWIW I had to update to rcpp 1.1.1-1.1 to avoid this.
